const $=id=>document.getElementById(id);
const departments=["الإدارة العامة للأمر بالمعروف والنهي عن المنكر","مركز التوعية","مكتب الإهداء","مكتب إرشاد الزائرين","مكتب إجابة السائلين"];
const logoSrc="../assets/religious-affairs-logo.jpg";
let employees=(window.EMPLOYEES||[]).map((x,i)=>({id:String(i),name:x[0],dept:x[1]||departments[0],selected:true}));
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
function norm(s){return String(s??"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/[ًٌٍَُِّْـ]/g,"").replace(/[\s\u200f\u200e]+/g," ").replace(/[،,.;:()\[\]{}]/g,"").trim();}
function formatDate(v){let p=String(v||"").split("-");return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:(v||"");}
function deptText(d){return d===departments[0]?"مترجم في الإدارة العامة للأمر بالمعروف والنهي عن المنكر":d;}
function options(sel){return departments.map(d=>`<option ${d===sel?"selected":""}>${esc(d)}</option>`).join("");}
function renderList(){let box=$("employeeList"),head=box.querySelector(".emp-head").outerHTML,q=norm($("search").value),rows="";employees.forEach((e,i)=>{if(q&&!norm(e.name).includes(q))return;rows+=`<div class="emp-row" data-index="${i}"><input class="emp-check" type="checkbox" ${e.selected?"checked":""}><span class="emp-num">${i+1}</span><input class="emp-name" value="${esc(e.name)}"><select class="emp-dept">${options(e.dept)}</select><button type="button" class="mini danger emp-delete">حذف</button></div>`});box.innerHTML=head+rows;bindRows();updateNumbers();}
function bindRows(){document.querySelectorAll(".emp-row").forEach(row=>{let i=+row.dataset.index;row.querySelector(".emp-check").onchange=e=>{employees[i].selected=e.target.checked;updateAll(false)};row.querySelector(".emp-name").oninput=e=>{employees[i].name=e.target.value;updateAll(false)};row.querySelector(".emp-dept").onchange=e=>{employees[i].dept=e.target.value;updateAll(false)};row.querySelector(".emp-delete").onclick=()=>{employees.splice(i,1);renderList();renderCards()};});}
function sizeName(n){return n.length>33?"9.6pt":n.length>27?"10.4pt":n.length>21?"11.5pt":"13pt"}
function sizeDept(d){return d.length>58?"7.7pt":d.length>44?"8.4pt":d.length>30?"9.8pt":"11pt"}
function cardHtml(name,dept,title,date,footer){let d=deptText(dept);return `<div class="card"><div class="card-title">${esc(title)}</div><div class="logo-area"><img src="${logoSrc}"></div><div class="gold-ornament">◆ ───── ◆ ───── ◆</div><div class="name-band" style="font-size:${sizeName(name)}">${esc(name)}</div><div class="dept" style="font-size:${sizeDept(d)}">${esc(d)}</div><div class="exp"><small>تاريخ انتهاء البطاقة</small><b>${esc(date)}</b></div><div class="footer">${esc(footer)}</div></div>`;}
function renderCards(){let title=$("cardTitle").value||"بطاقة مترجم",date=formatDate($("expiryDate").value),footer=$("footerText").value||"";let selected=employees.filter(e=>e.selected&&e.name.trim());let out="";for(let i=0;i<selected.length;i+=9)out+=`<div class="print-page">${selected.slice(i,i+9).map(e=>cardHtml(e.name.trim(),e.dept,title,date,footer)).join("")}</div>`;$("a4").innerHTML=out||'<div class="print-page"><div class="size-test">لا توجد أسماء محددة</div></div>';}
function updateNumbers(){let total=employees.length,sel=employees.filter(e=>e.selected).length;$("totalCount").textContent=total;$("selectedCount").textContent=sel;$("pageCount").textContent=Math.max(1,Math.ceil(sel/9));$("statusBox").textContent=`الأسماء ظاهرة الآن داخل الصفحة. عدد الأسماء: ${total}`;}
function updateAll(rerenderList=false){if(rerenderList)renderList();updateNumbers();renderCards();}
function selectAll(v){employees.forEach(e=>e.selected=v);renderList();renderCards();}
function invertSelection(){employees.forEach(e=>e.selected=!e.selected);renderList();renderCards();}
function addOneName(name,dept){name=String(name||"").replace(/^\s*\d+[\-.\)]?\s*/,"").trim();if(!name)return false;let k=norm(name);if(employees.some(e=>norm(e.name)===k))return false;employees.push({id:String(Date.now()+Math.random()),name,dept,selected:true});return true;}
function addPastedNames(){let added=0,dept=$("defaultDept").value;$("pasteNames").value.split(/\r?\n/).forEach(line=>{if(addOneName(line,dept))added++});alert(`تمت إضافة ${added} اسم جديد.`);renderList();renderCards();}
function selectPastedNames(){let keys={};$("pasteNames").value.split(/\r?\n/).forEach(line=>{let n=line.replace(/^\s*\d+[\-.\)]?\s*/,"").trim();if(n)keys[norm(n)]=true;});employees.forEach(e=>e.selected=!!keys[norm(e.name)]);renderList();renderCards();}
const PRINT_CSS=`@page{size:A4 portrait;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;width:210mm;background:#fff;font-family:Tahoma,Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.print-page{width:210mm;height:297mm;margin:0;padding:14.5mm 18mm;display:grid;grid-template-columns:54mm 54mm 54mm;grid-template-rows:86mm 86mm 86mm;column-gap:6mm;row-gap:5mm;align-content:start;justify-content:center;background:#fff;overflow:hidden;page-break-after:always;break-after:page}.print-page:last-child{page-break-after:auto;break-after:auto}.card{width:54mm;height:86mm;min-width:54mm;max-width:54mm;min-height:86mm;max-height:86mm;margin:0;padding:0;background:#fff;border:1.25px solid #a88b2d;position:relative;overflow:hidden;text-align:center;display:flex;flex-direction:column;page-break-inside:avoid;break-inside:avoid}.card-title{height:6.4mm;background:#004b3c;color:#fff;display:flex;align-items:center;justify-content:center;font-size:10.8pt;font-weight:900;border-top:1.2px solid #a88b2d;border-bottom:1px solid #a88b2d}.logo-area{height:18.2mm;background:#fff;display:flex;align-items:center;justify-content:center;padding:1.8mm 2mm 1mm}.logo-area img{max-width:39mm;max-height:14.8mm;object-fit:contain}.gold-ornament{height:3.6mm;background:#fff;display:flex;align-items:center;justify-content:center;color:#a88b2d;font-size:6.8pt;font-weight:900;letter-spacing:.2mm}.name-band{height:15.5mm;background:#004b3c;color:#fff;display:flex;align-items:center;justify-content:center;padding:1.2mm 2mm;font-weight:900;line-height:1.25;border-top:1px solid #a88b2d;border-bottom:1px solid #a88b2d}.dept{height:17mm;background:#f1ead7;display:flex;align-items:center;justify-content:center;padding:1.2mm 2mm;color:#053f34;font-weight:900;line-height:1.22;border-bottom:1px solid #d7c485}.exp{height:13.8mm;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#004b3c;font-weight:900;line-height:1.15}.exp small{display:block;font-size:9.8pt;font-weight:900;margin-bottom:1mm}.exp b{font-size:12.5pt;color:#a88b2d;font-weight:900}.footer{height:11.5mm;margin-top:auto;background:#004b3c;color:#fff;display:flex;align-items:center;justify-content:center;padding:1mm 2mm;font-size:8.5pt;font-weight:800;line-height:1.28;border-top:1px solid #a88b2d}`;
function printCardsOnly(){updateAll(false);let cardsHtml=$("a4").innerHTML;if(!cardsHtml.includes("card")){alert("لا توجد بطاقات محددة للطباعة.");return;}let old=document.getElementById("printOnlyFrame");if(old)old.remove();let iframe=document.createElement("iframe");iframe.id="printOnlyFrame";iframe.style.cssText="position:fixed;left:-10000px;top:0;width:0;height:0;border:0";document.body.appendChild(iframe);let doc=iframe.contentWindow.document;doc.open();doc.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>طباعة البطاقات</title><style>${PRINT_CSS}</style></head><body>${cardsHtml}</body></html>`);doc.close();setTimeout(()=>{iframe.contentWindow.focus();iframe.contentWindow.print();},350);}
function downloadStandalone(){updateAll(false);let html="<!doctype html>\n"+document.documentElement.outerHTML;let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));a.download="بطاقات_المترجمين.html";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1000);}
function init(){$("defaultDept").innerHTML=options(departments[0]);["cardTitle","expiryDate","footerText"].forEach(id=>$(id).addEventListener("input",()=>updateAll(false)));$("search").addEventListener("input",renderList);$("refreshBtn").onclick=()=>updateAll(true);$("printBtn").onclick=printCardsOnly;$("downloadBtn").onclick=downloadStandalone;$("selectAllBtn").onclick=()=>selectAll(true);$("clearAllBtn").onclick=()=>selectAll(false);$("invertBtn").onclick=invertSelection;$("addNamesBtn").onclick=addPastedNames;$("selectPastedBtn").onclick=selectPastedNames;renderList();renderCards();}
try{init();}catch(err){console.error(err);$("statusBox").textContent="تعذر تحميل المعاينة، لكن الأسماء موجودة في البيانات.";}
